<table>
    <tr>
        <th></th>
        <th>Modelo</th>
        <th>Ano</th>
        <th>Placa</th>
        <th><a href="<?= $this->c() ?>" class="ajax create"><img src="<?= $this->di() ?>" alt="adicionar" /></a></th>
    </tr>


<?php foreach($this->records as $i => $record) : ?>
    <?php $id = $record->id ?>
    <tr class="r<?= ($i%2) ?>">
        <td><?= $this->cc($id) ?></td>
        <td><?= $record->modelo ?></td>
        <td><?= $record->ano ?></td>
        <td><?= $record->placa ?></td>



        <td>
            <?php $url = $this->crudUrl ?>
            <a href="<?= $this->d($id) ?>" class="ajax delete"><img src="<?= $this->di() ?>" alt="excluir" /></a>
            <a href="<?= $this->u($id) ?>" class="ajax update"><img src="<?= $this->ui() ?>" alt="editar" /></a>
            <a href="<?= $this->r($id) ?>" class="ajax read"><img src="<?= $this->ri() ?>" alt="visualizar" /></a>
        </td>
    </tr>
<?php endforeach ?>


</table>