<?php

/**
 * Imagem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Imagem extends Base_Imagem
{

    protected $_oldFilename;

    public function preDelete()
    {
        $this->_oldFilename = $this->arquivo;
    }

    public function postDelete()
    {
        App_Image::getInstance()->removeImage($this->_oldFilename);
    }

}