<?php

/**
 * Marca
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Marca extends Base_Marca
{

    /**
     * pre save rotines.
     */
    public function preSave()
    {
        if ($this->isModified()) {
            $this->calculateUrl();
        }
    }

    /**
     * calculates and sets url
     */
    private function calculateUrl()
    {
        $modified = $this->getModified();

        if (array_key_exists('nome', $modified)) {
            $url = Util_String::toUrl($this->nome);
            $this->_set('url', $url);
            foreach ($this->Veiculos as $veiculo) {
                //loop to force changes
            }
        }
    }

}