<?php

/**
 * Veiculo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Veiculo extends Base_Veiculo
{
    const VEHICLE_STATUS_AVAILABLE = 1;
    const VEHICLE_STATUS_CANCELED = 2;
    const VEHICLE_STATUS_SOLD = 3;

    /**
     * Get the main image
     * @return Doctrine_Record|stdClass
     */
    public function getImage()
    {
        $imagens = $this->Imagens;

        if ($imagens->count()) {
            return $imagens[0];
        }

        return false;
    }

    /**
     * pre save rotines.
     */
    public function preSave()
    {
        $this->_calculateUrl();
        $this->_changeStatusDate();
    }

    /**
     * calculates and sets url
     */
    private function _calculateUrl()
    {
        $urlParts = array(
            $this->Marca->nome,
            $this->modelo,
            $this->placa,
        );

        $url = App_String::arrayToUrl($urlParts);
        $url = trim($url, '/');
        $this->_set('url', $url);
    }

    /**
     * Get formated price
     * @return string
     */
    public function getValor()
    {
        $value = $this->_get('valor');
        $options = array(
            'format' => 'pt_BR',
            'display' => Zend_Currency::NO_SYMBOL,
        );
        $cur = new Zend_Currency();
        return $cur->toCurrency($value, $options);
    }

    /**
     *
     * @param string $value
     */
    public function setValor($value)
    {
        $value = str_replace('.', '', $value);
        $value = str_replace(',', '.', $value);
        $this->_set('valor', $value);
    }

    /**
     * change the date the vehicle had the satus changed
     */
    private function _changeStatusDate()
    {
        $modified = $this->getModified();

        if (array_key_exists('situacao_id', $modified)) {
            if ($this->situacao_id !== self::VEHICLE_STATUS_AVAILABLE) {
                $date = new Zend_Date();
                $this->situacao_modificada_em = $date->toString('YYYY-MM-dd HH:mm:ss');
            }
        }
    }

    /**
     * Get situacao modificada em
     * @return string
     */
    public function getSituacaoModificadaEm()
    {
        return $this->_getBrDateTime('situacao_modificada_em');
    }

    /**
     * Get situacao created at
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->_getBrDateTime('created_at');
    }

    /**
     * Get situacao updated at
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->_getBrDateTime('updated_at');
    }

    /**
     * Get br date time
     * @param string $field
     * @return string
     */
    private function _getBrDateTime($field)
    {
        $date = new Zend_Date($this->_get($field, 'YYYY-MM-dd HH:mm:ss'));
        return $date->toString('dd/MM/YYYY HH:mm:ss');
    }

}