<?php

/**
 * VeiculoCaracteristica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VeiculoCaracteristica extends Base_VeiculoCaracteristica
{

    public function setOrdem($value)
    {
        $this->_set('ordem', (int) $value);
    }

}