
    <div id="search">
        <?= new Admin_Form_Search() ?>
    </div>

<div class="messages-container"></div>
<div class="clear"></div>

    <table>
        <tr>
            <th class="id all"><?= $this->cc('all') ?></th>
            <th><?= $this->order('Ordem') ?></th>
            <th><?= $this->order('Descricao') ?></th>
            <th><?= $this->order('Alt') ?></th>
            <th><?= $this->order('Title') ?></th>
            <th><?= $this->order('Ilustrativa') ?></th>
            <th>Imagem</th>
            <th class="actions">
                <a href="<?= $this->c() ?>" class="ajax create"><img src="<?= $this->ci() ?>" alt="adicionar" /></a>
            </th>
        </tr>


    <?php foreach($this->records as $i => $record) : ?>
        <?php $id = $record->id ?>
        <tr class="<?= ($i%2) ? 'alt' : '' ?>">
            <td class="id"><?= $this->cc($id) ?></td>
            <td><?= $record->ordem ?></td>
            <td><?= $record->descricao ?></td>
            <td><?= $record->alt ?></td>
            <td><?= $record->title ?></td>
            <td><?= $record->ilustrativa ? 'Sim' : 'Não' ?></td>
            <td><img src="<?= $this->image($record->Imagem->arquivo, '100x66') ?>"
                     title="<?= $record->title ?>"
                     alt="<?= $record->alt ?>"/>
            </td>
            <td class="actions">
                <?php $url = $this->crudUrl ?>
                <a href="<?= $this->u($id) ?>" title="editar" class="ajax update"><img src="<?= $this->ui() ?>" title="editar" alt="editar" /></a>
                <a href="<?= $this->d($id) ?>" title="excluir" class="ajax delete"><img src="<?= $this->di() ?>" title="excluir" alt="excluir" /></a>
            </td>
        </tr>
    <?php endforeach ?>
    </table>

    <?= $this->pagination()->render() ?>