<?php

/**
 * Base_ExceptionLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $parameters
 * @property string $exception
 * @property string $message
 * @property text $stack_trace
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_ExceptionLog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('exception_log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('parameters', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('exception', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('stack_trace', 'text', null, array(
             'type' => 'text',
             ));


        $this->index('search', array(
             'fields' => 
             array(
              'exception' => 
              array(
              ),
              'message' => 
              array(
              ),
              'parameters' => 
              array(
              ),
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}