<?php

/**
 * Base_Imagem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $arquivo
 * @property string $md5
 * @property string $descricao
 * @property Doctrine_Collection $VeiculoImagem
 * @property Doctrine_Collection $Marcas
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Imagem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('imagem');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('arquivo', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('md5', 'string', 32, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '32',
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));


        $this->index('descricao', array(
             'fields' => 
             array(
              0 => 'descricao',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VeiculoImagem', array(
             'local' => 'id',
             'foreign' => 'imagem_id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Marca as Marcas', array(
             'local' => 'id',
             'foreign' => 'imagem_id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}