<?php

/**
 * Base_VeiculoImagem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $veiculo_id
 * @property integer $imagem_id
 * @property integer $ordem
 * @property boolean $ilustrativa
 * @property string $alt
 * @property string $title
 * @property string $descricao
 * @property Veiculo $Veiculo
 * @property Imagem $Imagem
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_VeiculoImagem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('imagem_veiculo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('veiculo_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('imagem_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('ordem', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('ilustrativa', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('alt', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('veiculo_imagem', array(
             'fields' => 
             array(
              'imagem_id' => 
              array(
              ),
              'veiculo_id' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Veiculo', array(
             'local' => 'veiculo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Imagem', array(
             'local' => 'imagem_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}