<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta()
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
            ->appendHttpEquiv('Content-Language', 'pt_BR') ?>
        <?= $this->headLink()
                ->appendStylesheet($this->baseUrl('/css/black-tie/jquery-ui-1.7.3.custom.css'))
                ->appendStylesheet($this->baseUrl('/css/style.css'))
                    ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
        <?= $this->jQuery()->setVersion('1.4')->uiEnable()->setUiVersion('1.7.2'); ?>
        <link rel="SHORTCUT ICON" href="/public/images/icon.ico" type="image/x-icon" />
        <script type="text/javascript" src="<?= $this->baseUrl();?>/js/forms.js" charset="UTF-8"></script>
    </head>
    <body>
        <div id="content">
            <div id="menuTop">
                <?= $this->navigation(App_Navigation_Menu::get('Admin_Menu_Top'))->menu() ?>

                <div id="view"><?php echo $this->layout()->content; ?></div>
            </div>
        </div>
        <div id="dialog"></div>

    </body>
</html>