<div id="search">
    <?= new Admin_Form_Search() ?>
</div>

<div class="messages-container"></div>
<div class="clear"></div>

<table>
    <tr>
        <th class="id all"><?= $this->cc('all') ?></th>
        <th><?= $this->order('Nome') ?></th>
        <th class="actions">
            <a href="<?= $this->c() ?>" class="ajax create"><img src="<?= $this->ci() ?>" alt="adicionar" /></a>
        </th>
    </tr>


<?php foreach($this->records as $i => $record) : ?>
    <?php $id = $record->id ?>
    <tr class="<?= ($i%2) ? 'alt' : '' ?>">
       <td class="id"><?= $this->cc($id) ?></td>
       <td><?= $record->nome ?></td>

        <td class="actions">
            <a href="<?= $this->u($id) ?>" title="editar" class="ajax update"><img src="<?= $this->ui() ?>" title="editar" alt="editar" /></a>
            <a href="<?= $this->d($id) ?>" title="excluir" class="ajax delete"><img src="<?= $this->di() ?>" title="excluir" alt="excluir" /></a>
        </td>
    </tr>
<?php endforeach ?>
</table>

<?= $this->pagination()->render() ?>