<div id="search">
    <?= new Admin_Form_Search() ?>
</div>

<table>
    <tr>
        <th><?= $this->order('Descrição','descricao') ?>
            <a href="<?= $this->c() ?>" class="ajax create">
                <img src="<?= $this->ci() ?>" alt="adicionar" />
            </a>
        </th>
    </tr>
    <tr>
       <td class="images">
           <ul class="images">
                <?php foreach($this->records as $i => $record) : ?>
                   <li>
                       <?php $id = $record->id ?>

                       <div class="image">
                           <img title="<?= $record->descricao ?>" alt="<?= $record->descricao ?>" src="<?= $this->image($record->arquivo, '200x134') ?>" />
                       </div>

                       <div class="description"><?= $record->descricao ?></div>
                       <div class="actions">
                           <?= $this->cc($id) ?>
                           <a href="<?= $this->u($id) ?>" title="editar" class="ajax update"><img src="<?= $this->ui() ?>" title="editar" alt="editar" /></a>
                           <a href="<?= $this->d($id) ?>" title="excluir" class="ajax delete"><img src="<?= $this->di() ?>" title="excluir" alt="excluir" /></a>
                       </div>
                   </li>
                <?php endforeach ?>
           </ul>
        </td>
    </tr>
</table>

<?= $this->pagination()->render() ?>