<div id="search">
    <?= new Admin_Form_Search() ?>
</div>

<table>
    <tr>
        <th class="id all"><?= $this->cc('all') ?></th>
        <th><?= $this->order('Marca') ?></th>
        <th><?= $this->order('Tipo') ?></th>
        <th><?= $this->order('Modelo') ?></th>
        <th><?= $this->order('Cor') ?></th>
        <th><?= $this->order('Ano/Mod.','Ano') ?></th>
        <th><?= $this->order('Comb.','combustivel') ?></th>
        <th><?= $this->order('Placa') ?></th>
        <th><?= $this->order('Valor') ?></th>
        <th><?= $this->order('Situação','situacao') ?></th>
        <th class="actions">
            <a href="<?= $this->c() ?>" class="ajax create"><img src="<?= $this->ci() ?>" alt="adicionar" /></a>
        </th>
    </tr>


<?php foreach($this->records as $i => $record) : ?>
    <?php $id = $record->id ?>
    <tr class="<?= ($i%2) ? 'alt' : '' ?>">
        <td class="id"><?= $this->cc($id) ?></td>
        <td><?= $record->Marca->nome ?></td>
        <td><?= $record->Tipo->nome ?></td>
        <td><?= $record->modelo ?></td>
        <td><?= $record->cor ?></td>
        <td class="center"><?= $record->ano ?>/<?= $record->ano_modelo ?></td>
        <td class="center"><?= $record->Combustivel->abreviacao ?></td>
        <td class="center"><?= $record->placa ?></td>
        <td class="right"><?= $record->valor ?></td>
        <td><?= $record->Situacao->nome ?></td>



        <td class="actions">
            <?php $url = $this->crudUrl ?>
            <a href="<?= $this->r($id) ?>" title="visualizar" class="ajax read"><img src="<?= $this->ri() ?>" title="visualizar" alt="visualizar" /></a>
            <a href="<?= $this->u($id) ?>" title="editar" class="ajax update"><img src="<?= $this->ui() ?>" title="editar" alt="editar" /></a>
            <a href="<?= $this->d($id) ?>" title="excluir" class="ajax delete"><img src="<?= $this->di() ?>" title="visualizar" alt="excluir" /></a>
        </td>
    </tr>
<?php endforeach ?>
</table>

<?= $this->pagination()->render() ?>